use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, exit};

const SHADER_FILES: &[&str] = &[
    "rasterzation.comp",
];

fn main() {
    let out_dir = PathBuf::from("./target/shaders/");
    let shader_dir = Path::new("src").join("shaders");
    fs::create_dir_all(&out_dir).unwrap();

    for &file in SHADER_FILES {
        let src_path = shader_dir.join(file);
        if !src_path.exists() {
            eprintln!("Shader source not found: {}", src_path.display());
            exit(1);
        }
        let out_name = Path::new(file).with_extension("spv");
        let out_path = out_dir.join(&out_name);

        let status = Command::new("glslc")
            .arg(&src_path)
            .arg("-o")
            .arg(&out_path)
            .status()
            .unwrap_or_else(|e| {
                eprintln!("Failed to execute glslc: {}", e);
                eprintln!("Make sure glslc is installed and available in your PATH.");
                exit(1);
            });
        if !status.success() {
            eprintln!("glslc failed for {}", src_path.display());
            exit(1);
        }
        println!("cargo:rerun-if-changed={}", src_path.display());
    }

    let native_dir = Path::new("src").join("native");
    fs::create_dir_all(&native_dir).unwrap();
    let mod_path = native_dir.join("shaders.rs");

    let mut mod_content = String::new();
    mod_content.push_str("// Auto-generated by build.rs\n");
    mod_content.push_str("use vulkanalia::include_shader_code;\n\n");

    for &file in SHADER_FILES {
        let stem = Path::new(file).file_stem().unwrap().to_string_lossy();
        let ident = stem.replace('-', "_").to_uppercase();
        let spv_file = Path::new(file).with_extension("spv");
        let abs_path = out_dir.join(&spv_file).to_str().unwrap().replace('\\', "/");
        mod_content.push_str(&format!(
            "pub const {}: &[u32] = include_shader_code!(\"{}\");\n",
            ident, "../.".to_string()+&abs_path
        ));
    }

    fs::write(&mod_path, mod_content).unwrap();
    println!("cargo:rerun-if-changed=src/shaders");
}